In [1]:
import pandas as pd

In [2]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow'
url = f'{prefix}/yellow_tripdata_2021-01.csv.gz'
url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz'

In [3]:
df = pd.read_csv(url)

/tmp/ipykernel_8493/4176769558.py:1: DtypeWarning: Columns (6: store_and_fwd_flag) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

In [4]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [5]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates
)

In [6]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [7]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi')

In [9]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [11]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000
)

In [40]:
from tqdm.auto import tqdm

In [42]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]

In [37]:
df = next(df_iter)

In [38]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
1200000,1,2021-01-29 19:29:55,2021-01-29 19:39:36,1,2.30,1,N,163,263,1,9.50,3.5,0.5,3.45,0.0,0.3,17.25,2.5
1200001,1,2021-01-29 19:47:01,2021-01-29 20:04:20,1,5.70,1,N,141,148,1,19.50,3.5,0.5,3.57,0.0,0.3,27.37,2.5
1200002,2,2021-01-29 19:10:30,2021-01-29 19:20:12,1,2.20,1,N,90,48,1,9.50,1.0,0.5,2.76,0.0,0.3,16.56,2.5
1200003,2,2021-01-29 19:29:00,2021-01-29 19:41:05,1,2.42,1,N,163,234,1,10.50,1.0,0.5,2.96,0.0,0.3,17.76,2.5
1200004,2,2021-01-29 19:58:45,2021-01-29 20:08:25,1,2.50,1,N,170,236,1,9.50,1.0,0.5,2.07,0.0,0.3,15.87,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1299995,<NA>,2021-01-05 09:09:00,2021-01-05 09:33:00,<NA>,8.82,<NA>,<NA>,238,241,<NA>,51.05,0.0,0.5,2.75,0.0,0.3,54.60,0.0
1299996,<NA>,2021-01-05 10:01:31,2021-01-05 10:01:04,<NA>,5.74,<NA>,<NA>,265,51,<NA>,15.20,0.0,0.5,0.00,0.0,0.3,16.00,0.0
1299997,<NA>,2021-01-05 10:01:12,2021-01-05 10:01:03,<NA>,2.70,<NA>,<NA>,265,174,<NA>,15.20,0.0,0.5,0.00,0.0,0.3,16.00,0.0
1299998,<NA>,2021-01-05 10:48:00,2021-01-05 10:56:00,<NA>,1.37,<NA>,<NA>,15,15,<NA>,20.97,0.0,0.5,2.75,0.0,0.3,24.52,0.0
1299999,<NA>,2021-01-05 10:08:00,2021-01-05 10:16:00,<NA>,1.71,<NA>,<NA>,155,210,<NA>,24.42,0.0,0.5,2.75,0.0,0.3,27.97,0.0